name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  advanced_dbt:
    +materialized: view
    +grants:
      select: ['transformer', 'reporter']

seeds:
  unit_testing_mrr:
    unit_testing:
      +schema: unit_testing
      +tags: unit_testing
      unit_test_input_dim_subscriptions:
        +column_types:
          subscription_id: INTEGER
          user_id: INTEGER
          starts_at: TIMESTAMP
          ends_at: TIMESTAMP
          plan_name: STRING
          pricing: STRING
          billing_period: STRING
      unit_test_input_dim_dates:
        +column_types:
          calendar_date: DATE
          day_of_month: INTEGER
      unit_test_expected_output_mrr:
        +column_types:
          date_month: DATE
          user_id: INTEGER
          subscription_id: INTEGER
          starts_at: TIMESTAMP
          ends_at: TIMESTAMP
          plan_name: STRING
          mrr_amount: FLOAT
          mrr_change: STRING
          retained_mrr_amount: FLOAT
          previous_month_mrr_amount: FLOAT
          change_category: STRING
          month_retained_number: INTEGER
          surrogaye_key: STRING
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues(format='csv') }}"
